# Use an official Python runtime as a parent image
FROM python:3.12

LABEL maintainer="Syed Safdar Ali Shah"
# Set the working directory in the container
WORKDIR /code


# Install uv
RUN pip install uv

# Copy the current directory contents into the container at /code
COPY . /code/


# Install dependencies including development ones
RUN uv add fastapi uvicorn

# Make port 8000 available to the world outside this container
EXPOSE 8181

# Run the app. CMD can be overridden when starting the container
CMD ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8181", "--reload"]
































# FROM ubuntu

# # Install essential packages
# RUN apt-get update && \
#     apt-get install -y python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools curl bash

# # Install uv package manager
# RUN curl -LsSf https://astral.sh/uv/install.sh | bash

# # Add uv to PATH
# ENV PATH="/root/.cargo/bin:$PATH"

# # Set the working directory
# WORKDIR /fastapi-docker

# # Copy the project files into the container
# COPY . /fastapi-docker/

# # Expose the port FastAPI will run on
# EXPOSE 8000

# # Run the FastAPI app using uv
# CMD ["bash ", "-c ", "uv ","run ","fastapi ","dev ","__init__.py"]
