FROM ubuntu

# Install essential packages
RUN apt-get update && \
    apt-get install -y python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools curl bash

# Install uv package manager
RUN curl -LsSf https://astral.sh/uv/install.sh | bash

# Add uv to PATH
ENV PATH="/root/.cargo/bin:$PATH"

# Set the working directory
WORKDIR /fastapi-docker

# Copy the project files into the container
COPY . /fastapi-docker/

# Expose the port FastAPI will run on
EXPOSE 8000

# Run the FastAPI app using uv
CMD ["bash ", "-c ", "uv ","run ","fastapi ","dev ","__init__.py"]
